version: "3"
services:
  App1:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - web
    depends_on:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  App2:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - web
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  web:
    driver: overlay