version: "3"
services:
  haproxy:
    image: dockercloud/haproxy
    depends_on:
      - awesome
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
  logdna:
        image: logdna/logspout:latest
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - LOGDNA_KEY=f9518ef4b413a048b6cc464c2498038b
networks:
  web:
    driver: overlay